# This config is used when building from the workspace root.
# The firmware crate has its own .cargo/config.toml that sets the Xtensa target.

[target.xtensa-esp32s3-none-elf]
runner = "espflash flash --monitor"
rustflags = ["-C", "link-arg=-nostartfiles"]

[env]
WIFI_SSID = "WLAN14192654"
WIFI_PASSWORD = "xssaMcTc5kjf"
# WIFI_SSID = "FRITZ!Box 7583 DR"
# WIFI_PASSWORD = "35385987231661973116"
