//! Core 1 — The Muscle.
//!
//! Runs hard real-time Embassy tasks for motor control, sensor polling, and
//! balancing.  This core operates **completely independently** of Core 0: it
//! does not share any mutable state with the Wasm engine or the ESP-NOW radio.
//!
//! ## Phase 3 implementation
//!
//! Core 1 polls the IMU every [`RT_LOOP_PERIOD_MS`] (2 ms = 500 Hz) and
//! publishes the result to [`crate::sensors::IMU_DATA`] via a single atomic
//! store.  Core 0 reads this value through the ABI without ever touching a
//! mutex or suspending.
//!
//! The simulated IMU values below will be replaced by real I2C/SPI reads
//! once the physical MPU-6050 (or equivalent) is wired up.
//!
//! ## Phase 4 implementation
//!
//! Core 1 now runs the full motor control pipeline each tick:
//!
//! 1. Read pitch/roll from the IMU.
//! 2. Check the ULP voltage flag — disable motors on critical voltage.
//! 3. Run the PID balance controller to compute a PWM output.
//! 4. Blend the PID output with any steering command from Core 0 (Wasm ABI).
//! 5. Apply the blended duty cycles to the motor PWM hardware.
//!
//! The Wasm sandbox on Core 0 can only influence the *steering offset*; it
//! cannot override the balancing loop or exceed the PWM clamps.
use embassy_time::{Duration, Timer};
use embassy_sync::{
    blocking_mutex::raw::CriticalSectionRawMutex,
    channel::Channel,
};

/// A command intent generated by Core 0 (e.g. from Wasm or Network) to be processed by Core 1.
#[derive(Clone, Copy)]
pub struct CommandIntent {
    pub intent_type: u8,
    // Add additional payload fields as needed
}

/// Channel to send commands from Core 0 to Core 1 Command Dispatcher
pub static COMMAND_DISPATCH_CHANNEL: Channel<CriticalSectionRawMutex, CommandIntent, 8> = Channel::new();

#[embassy_executor::task]
pub async fn command_dispatcher_task() {
    log::info!("[core1] Command dispatcher task started");
    let receiver = COMMAND_DISPATCH_CHANNEL.receiver();

    loop {
        match embassy_time::with_timeout(
            Duration::from_millis(1000),
            receiver.receive(),
        ).await {
            Ok(intent) => {
                log::info!("[core1] Received command intent: {}", intent.intent_type);
                // Dispatch command down to the Head OS via ESP-NOW radio or UART serial link
                // e.g. send over UART or ESP-NOW queue
            }
            Err(_) => {
                // Timeout, do background maintenance if needed
            }
        }
    }
}

